server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: canvas
          uri: lb://canvas
          predicates:
            - Path=/api/v1/canvas/**

        - id: cursor
          uri: lb://canvas
          predicates:
            - Path=/api/v1/cursor/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.87:8761/eureka/