spring:
  application:
    name: user
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
jwt:
  secret: ogerpon

mail:
  host: smtp.gmail.com
  port: 587
  username: slave102446@gmail.com
  password: mnhx lqsa skgr ksji
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?