spring:
  application:
    name: user

mail:
  host: smtp.gmail.com
  port: 587
  username: slave102446@gmail.com
  password: mnhx lqsa skgr ksji
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?