spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul
    username: root
    password: dPdmsdk?0928
  jpa:
    hibernate:
      ddl-auto: update  # 필요에 따라 설정 (create, update, validate, none 등)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8761  # Eureka 서버 기본 포트

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost  # 다른 PC들이 이 주소로 Eureka에 접근할 수 있게 설정
  server:
    enable-self-preservation: false  # 클라이언트 접속 테스트 시 설정

jwt:
  secret: ogerpon

mail:
  host: smtp.gmail.com
  port: 587
  username: slave102446@gmail.com
  password: mnhx lqsa skgr ksji
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?