spring:
  application:
    name: canvas
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/canvas?serverTimezone=Asia/Seoul
    username: root
    password: 131072

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
